### ISSUE TITLE
코드 올라올 때 마다

### ISSUE THREAD

**Issue by agrajak** [five-per-week/algorithms#2]
README.md를 자동으로 만들어줘서
이때까지 누가 몇 문제 풀었고 저번주에는 누가 몇 문제 풀었고 어떤 문제 풀었고 요약해주면 재미있을 듯??

=> 요거를 오픈소스화 시켜서 다른 알고리즘 스터디에서도 사용할 수 있게 배포하면 재밌을 것 같음!!

**Comment by younho9** [comment]
오 ~ 👍 

그 각자 문제 풀이하면 PR을 하나씩 보내니까 Github API로 매주 올라온 PR 분석하면 누가 몇개의 PR 날렸는지 확인할 수 있지 않을까? ㅋㅋ

**Comment by agrajak** [comment]
오 ㅋㅋㅋㅋ 그렇게 하면 될듯!!
