### ISSUE TITLE
Github Action 오류

### ISSUE THREAD

**Issue by agrajak** [five-per-week/algorithms#20]
[링크](https://github.com/five-per-week/algorithms/runs/1155607244)
```
INPUT_PUSH_OPTIONS: 
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To https://github.com/five-per-week/algorithms
 ! [remote rejected] master -> master (protected branch hook declined)
```
여기서도 리뷰가 필요하구나.. ㅋㅋㅋ ㅠㅠ

**Comment by younho9** [comment]
[auto-commit - push-to-protected-branches](https://github.com/stefanzweifel/git-auto-commit-action#push-to-protected-branches)

**Comment by younho9** [comment]
protected-branch에 대해서는 `--force` 옵션을 써야하네

**Comment by younho9** [comment]
PR이 아니라 커밋 푸시인데 리뷰 필요하다는 에러 뜨는건 신기하다

**Comment by agrajak** [comment]
다 방법이 있었구나..

**Comment by younho9** [comment]
github action은 실패하면서 배우는거 같더라고 ㅎㅎ
