### ISSUE TITLE
간략한 Ground Rule을 포함하여 README 작성

### ISSUE THREAD

**Issue by younho9** [five-per-week/algorithms#4]
branch 명 규칙, commit 타입, 규칙 등을 정하면 좋을 것 같음!

생각해둔거는 이런데 더 추가할거 있으면 밑에 코멘트 달아줘~

- 문제 풀이 시
    - `닉네임/문제-출처/문제-번호` ex) `younho9/programmers/42576` 으로 문제 풀기
    - 상대방이 리뷰해야 머지 가능 (함께 공부하는 목적)
    -  완료하면 `Squash and Merge` 하기 
        - 문제 풀 때 자잘한 커밋들을 모아서 하나로 묶어줌 -> 깔끔하게 커밋 로그 관리
    - 문제 풀이 성공시 ✅ , 실패시 ❌ 를 커밋 맨 앞에 붙이기.
        - 일주일 동안 끙끙 앓아도 5문제 못풀 수 있으니 못풀어도 5문제 시도해보는게 중요하니까??

- 그 외
    - `타입명/브랜치에-대한-간략한-설명` ex) `docs/github-pr-template` 으로 브랜치 만들기
    - 커밋 타입
        - `docs` : 문서 작업
        - `env` : 환경 세팅

**Comment by younho9** [comment]
문제 풀이에 대한 커밋은 이렇게할까? `solved: 문제-출처 문제-번호 @푼사람 닉네임` 푼사람 이름이 바로 태그로 붙는게 멋있어

**Comment by agrajak** [comment]
LGTM 👍

**Comment by younho9** [comment]
글고 이전 PR에 대해 `Merge Request`를 사용했는데 `Squash and Merge`를 사용하는거 어떻게 생각해? 메인 브랜치에 커밋 로그가 깔끔하게 쌓이는게 좋더라고
[참고](https://meetup.toast.com/posts/122)

**Comment by agrajak** [comment]
와 이제 Github에서 Squash를 지원하나보네 ㅋㅋㅋㅋ 좋아 좋아

**Comment by younho9** [comment]
응 좋아좋아 ㅎㅎ
